export { default as Home } from './Home'
export { default as Settings } from './Settings'
export { default as Scan } from './Scan'
export { default as Purchase } from './Purchase'
export { default as Balance } from './Balance'
export { default as More } from './More'